[package]
name = "fafa-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "A developer toolbox desktop client"

[dependencies]
anyhow.workspace = true
argon2.workspace = true
base64.workspace = true
bcrypt.workspace = true
blake3.workspace = true
dirs.workspace = true
gpui.workspace = true
gpui_platform = { workspace = true, features = ["font-kit", "wayland"] }
gpui_util.workspace = true
heck.workspace = true
hex.workspace = true
jiff.workspace = true
md-5.workspace = true
percent-encoding.workspace = true
qrcode = { workspace = true, features = ["svg"] }
rust-embed = { workspace = true, features = ["include-exclude"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha1.workspace = true
sha2.workspace = true
sha3.workspace = true
sys-locale.workspace = true
tracing = { workspace = true, features = ["max_level_trace", "release_max_level_error"] }
tracing-appender.workspace = true
tracing-subscriber.workspace = true
uuid = { workspace = true, features = ["v4", "v7"] }

[lints]
workspace = true

[package.metadata.bundle]
name = "FaFa"
identifier = "com.shenghaiyang.fafa"
icon = ["resources/app-icon-512.png", "resources/app-icon-512@2x.png"]
copyright = "Copyright © 2026 shenghaiyang"
osx_minimum_system_version = "12.0"
