[workspace]
members = ["crates/fafa", "crates/fafa-desktop"]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2024"
rust-version = "1.97.1"
authors = ["shenghaiyang"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/shenghaiyang/fafa"
homepage = "https://github.com/shenghaiyang/fafa"

[workspace.dependencies]
anstream = "1.0.0"
anyhow = "1.0.104"
argon2 = "0.6.0-rc.8"
base64 = "0.23.1"
bcrypt = "0.19.3"
blake3 = "1.8.5"
clap = "4.5.57"
dirs = "6.0.0"
gpui = { git = "https://github.com/zed-industries/zed.git" }
gpui_platform = { git = "https://github.com/zed-industries/zed.git" }
gpui_util = { git = "https://github.com/zed-industries/zed.git" }
heck = "0.5.0"
hex = "0.4.3"
jiff = "0.2.35"
md-5 = "0.11.0"
owo-colors = "=4.3.0"
percent-encoding = "2.3.1"
qrcode = "0.14.1"
rust-embed = "8.12.0"
serde = "1.0.229"
serde_json = "1.0.151"
sha1 = "0.11.0"
sha2 = "0.11.0"
sha3 = "0.12.0"
strum = "0.28"
sys-locale = "0.3.2"
tracing = "0.1.44"
tracing-appender = "0.2.5"
tracing-subscriber = "0.3.23"
uuid = "1.24.0"

[workspace.lints.clippy]
inconsistent_struct_constructor = "warn"
unwrap_used = "deny"
todo = "deny"
type_complexity = "allow"
let_underscore_future = "allow"
single_range_in_vec_init = "allow"
too_many_arguments = "allow"
large_enum_variant = "allow"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
